# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73a1dfaaedd53cc3fc46fa31f8b26b4771b855a1d018768953fd067549a619f8660e16f20449ebefe94fcc1bbdff64f1d24be4ae743e5c06f08b9a72cadde5c2

test:
  secret_key_base: deee4a9b79d8e45496a981a13b9d3c12051fec4955753dc8399596510878925936a980b163d5a8a854f5b8456601df5877f4a92c5a71519c5b0f502196281e69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
